name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Debug: List available secrets (names only)
      - name: Debug Environment
        run: |
          echo "Available secrets:"
          echo "AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_BAY_0CAA7A400: [exists]"
          echo "GITHUB_TOKEN: [exists]"
          echo "Current directory:"
          pwd

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      # Build and publish
      - name: Build and Publish
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore
          dotnet publish -c Release -o published

      # Debug: List contents
      - name: List Directory Structure
        run: |
          echo "Root directory:"
          ls -la
          echo "Published directory:"
          ls -la published
          echo "Published wwwroot directory:"
          ls -la published/wwwroot

      # Deploy
      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_DUNE_08DFB2900 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "published/wwwroot"
          api_location: ""
          output_location: ""

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_DUNE_08DFB2900 }}
          action: "close"